In [1]:
import os
# import warnings
# warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import matplotlib.pylab as plt
import seaborn as sns

In [119]:
os.chdir('..')
df = pd.read_csv('Data/Properati_data_clean_dummy.csv')
os.chdir('Notebooks')
df.head()

,lat,lon,rooms,surface_total,surface_covered,price,surface_uncovered,Casa,Departamento,PH,...,VILLA GRAL. MITRE,VILLA LUGANO,VILLA LURO,VILLA ORTUZAR,VILLA PUEYRREDON,VILLA REAL,VILLA RIACHUELO,VILLA SANTA RITA,VILLA SOLDATI,VILLA URQUIZA
0,-34.601864,-58.443563,3.0,67.0,60.0,110000.0,7.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-34.644735,-58.421061,2.0,40.0,40.0,79900.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-34.603423,-58.431140,2.0,38.0,38.0,112000.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-34.609326,-58.492374,2.0,94.0,77.0,169000.0,17.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,-34.629607,-58.439279,1.0,41.0,37.0,118000.0,4.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [120]:
from sklearn.model_selection import train_test_split

# Shuffleamos
np.random.seed(seed=49)
df_perm = np.random.permutation(df)
df = pd.DataFrame(df_perm,columns=df.columns)

# Vamos a dividir en tres conjuntos: train, validation, test
df_train, df_2 = train_test_split(df,test_size=0.3,random_state=50)
df_validation, df_test = train_test_split(df_2,test_size=0.5,random_state=51)

In [121]:
# Tomaremos como target la variable precio, y como input todo lo demás
X_train = df_train.drop(columns=['price'])
X_validation = df_validation.drop(columns=['price'])
X_test = df_test.drop(columns=['price'])
y_train = df_train['price']
y_validation = df_validation['price'] 
y_test = df_test['price']

In [5]:
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.neighbors import KNeighborsRegressor as KNR
from sklearn.preprocessing import StandardScaler


# Estandarizamos los datos
scaler1 = StandardScaler()
scaler1.fit(X_train)
X_train_scaled = scaler1.transform(X_train)
X_test_scaled = scaler1.transform(X_test)
 
# Aplicamos KNN
knr1 = KNR()
knr1.fit(X_train_scaled,y_train)
y_train_pred_knr = knr1.predict(X_train_scaled)
y_test_pred_knr = knr1.predict(X_test_scaled)

# Calculamos RMSE y R2
rmse_knr_train = np.sqrt(mean_squared_error(y_train,y_train_pred_knr))
rmse_knr_test = np.sqrt(mean_squared_error(y_test,y_test_pred_knr))
r2_knr_train = r2_score(y_train,y_train_pred_knr)
r2_knr_test = r2_score(y_test,y_test_pred_knr)

# Output metricas
print(f"El RMSE en el conjunto de train es {rmse_knr_train}")
print(f"El RMSE en el conjunto de test es {rmse_knr_test}")
print(f"El R2 en el conjunto de train es {r2_knr_train}")
print(f"El R2 en el conjunto de test es {r2_knr_test}")

El RMSE en el conjunto de train es 28785.94269550513
El RMSE en el conjunto de test es 35564.833687529535
El R2 en el conjunto de train es 0.8795983634085449
El R2 en el conjunto de test es 0.8125567823873306

In [151]:
# Sampleamos
descarte,sample = train_test_split(df_test,test_size=0.03)
# sample = sample.reset_index(drop=True)
X_sample = sample.drop(columns=['price'])
X_sample_scaled = scaler1.transform(X_sample)
y_sample = sample.price

In [153]:
sample

,lat,lon,rooms,surface_total,surface_covered,price,surface_uncovered,Casa,Departamento,PH,...,VILLA GRAL. MITRE,VILLA LUGANO,VILLA LURO,VILLA ORTUZAR,VILLA PUEYRREDON,VILLA REAL,VILLA RIACHUELO,VILLA SANTA RITA,VILLA SOLDATI,VILLA URQUIZA
3496,-34.566778,-58.451738,3.0,120.0,120.0,310000.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7926,-34.600832,-58.371706,4.0,100.0,100.0,230000.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14706,-34.568596,-58.451195,3.0,102.0,95.0,298000.0,7.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12414,-34.608222,-58.378128,2.0,40.0,40.0,98000.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13444,-34.653881,-58.519300,4.0,110.0,97.0,230000.0,13.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1628,-34.597723,-58.430423,2.0,64.0,45.0,149500.0,19.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16264,-34.592398,-58.384312,3.0,53.0,48.0,190000.0,5.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
294,-34.629120,-58.460810,1.0,37.0,37.0,79000.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3201,-34.623096,-58.455462,3.0,109.0,86.0,350000.0,23.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7859,-34.608355,-58.400045,2.0,56.0,50.0,78000.0,6.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [152]:
y_sample[0:5]

3496     310000.0
7926     230000.0
14706    298000.0
12414     98000.0
13444    230000.0
Name: price, dtype: float64

In [158]:
X_sample.shape[0]

115

In [165]:
knr1.predict(X_sample_scaled)

array([368400. , 255600. , 302800. ,  90600. , 162200. , 324000. ,
       174000. , 133200. , 204000. , 149000. , 120000. , 151000. ,
       248800. , 103600. ,  94400. , 117800. , 101960. , 175800. ,
       117200. , 227200. , 255600. , 180304. , 130900. , 203800. ,
       119400. , 270800. , 111600. , 272380. , 274200. , 104400. ,
       111760. ,  79400. , 187000. ,  70800. , 158100. , 165000. ,
       253980. , 133500. , 158120. , 111438.8, 265000. , 188900. ,
       124400. , 188600. , 328560. ,  90400. , 196000. ,  73200. ,
       172660. , 159600. , 152600. , 194200. , 160780. , 175400. ,
       149600. , 120780. , 169600. , 101100. , 325800. , 125200. ,
        68600. , 113380. , 261200. , 215000. , 346000. , 147200. ,
       139400. , 155580. , 111600. , 156400. , 348200. , 357600. ,
       110200. , 224200. , 144400. , 145400. ,  79100. , 124493.2,
       120180. , 317000. ,  79000. , 127600. , 140800. ,  81380. ,
       139800. , 184800. , 271400. , 214800. ,  97180. , 247000. ,
       132200. , 120000. , 137000. , 180600. , 160800. , 157460. ,
       122700. , 107000. ,  99200. , 162600. , 171000. , 130980. ,
       102740. ,  97400. , 153200. , 175000. ,  98200. ,  97600. ,
       283600. , 131200. , 164020. , 193000. ,  85000. , 235960. ,
       130200. ])

In [167]:
predictions = knr1.predict(X_sample_scaled)
neighbors_ind = knr1.kneighbors(X_sample_scaled)[1]
# for i, j in zip(range(X_sample.shape[0]),X_sample.index):
# i = 7, j = 20751
obj = {}
neighbors = df.iloc[neighbors_ind[7],:]
neighbors['price_m2'] = round(neighbors['price'] / neighbors['surface_total'],2)
surf_mean = neighbors['surface_total'].mean()
price_m2_mean = neighbors['price_m2'].mean()
price_mean = neighbors['price'].mean()
price_m2_target = df.at[20751,'price'] / df.at[20751,'surface_total']
obj['neigh_lat_list'] = list(neighbors['lat'])
obj['neigh_lon_list'] = list(neighbors['lon'])
obj['neigh_price_m2_list'] = list(neighbors['price_m2'])
obj['neigh_surf_list'] = list(neighbors['surface_total']) 
obj['neigh_mean_surf'] = round(surf_mean)
obj['target_surf'] = df.at[20751,'surface_total']
obj['neigh_mean_price_m2'] = round(price_m2_mean,2)
obj['target_price_m2'] = round(price_m2_target,2)
obj['pred_price'] = predictions[7]
obj['target_price'] = df.at[20751,'price']

# obj['neighbors_coord'] =  
obj
# neighbors

C:\Users\Usuario\Python\Anaconda\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

{'neigh_lat_list': [-34.608106,
  -34.6097882311,
  -34.619771,
  -34.598356700000004,
  -34.545371],
 'neigh_lon_list': [-58.448199,
  -58.4159547095,
  -58.461248,
  -58.42175400000001,
  -58.476125],
 'neigh_price_m2_list': [2968.75, 2547.17, 2144.58, 2500.0, 2772.28],
 'neigh_surf_list': [32.0, 53.0, 83.0, 38.0, 101.0],
 'neigh_mean_surf': 61,
 'target_surf': 60.0,
 'neigh_mean_price_m2': 2586.56,
 'target_price_m2': 2000.0,
 'pred_price': 133200.0,
 'target_price': 120000.0}

In [18]:
for i in range(len(sample)):
    neighbors_ind = knr1.kneighbors(sample_scaled)[1][i]
    neighbors = X_train.iloc[neighbors_ind,:]
    neighbors

IndexError: single positional indexer is out-of-bounds